### ISSUE TITLE
Feature Request: Optionally disable rebuilding python packages

### ISSUE THREAD

**Issue by carlkibler** [serverless/serverless-python-requirements#142]
I would love speed up re-packaging of my project's python requirements by explicitly telling this plugin not to run sometimes. 

Example: When I'm on a slow internet connection I can avoid network requests. When I'm on battery can avoid the Docker invocation. Or just when reqs haven't changed.

As an example, would like to:
sls package --skip-python-requirements
sls deploy --skip-python-requirements
(or however params to plugin execution can be passed)

**Comment by dschep** [comment]
This would best be implemented as skipping the `pip` install step (rather disabling the plugin entirely) and still linking/unlinking from `.serverless/requirements`

**Comment by AndrewFarley** [comment]
Attempted to implement in #162 but it could use a flag and a lot of love.  Input invited.  :)

**Comment by AndrewFarley** [comment]
Some notes from my implementation, however, is that the .serverless folder is completely destroyed before passing context into this plugin.  So we can't use the previous data in .serverless/requirements.  At least, not to my knowledge.  See my comments on that PR for more details...

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
