### ISSUE TITLE
is there a way to also include pkg_resources

### ISSUE THREAD

**Issue by joycechangeorg** [serverless/serverless-python-requirements#163]
My python functions often doesn't work unless I also have  ./venv/lib/python2.7/site-packages/pkg_resources copy into the package

Can we have that copied by default or have an option to?

Thanks

**Comment by dschep** [comment]
Does including setuptools in your `requirements.txt` not work?

**Comment by joycechangeorg** [comment]
You're right, that does work, thank you

**Comment by dschep** [comment]
Excellent! Glad to hear that works :+1:

**Comment by Pjack** [comment]
I use version 4.0.0.
The solution doesn't work to me.
I found requirement.txt under .serverless/  (copied by the plugin) is different than original one.
pip, setuptool, python-dateutil will be removed.

Please let me know if it is an issue. 

Thanks!

**Comment by Pjack** [comment]
I add noDeploy option in serverless.yml  to overwrite the default list as the solution

**Comment by dschep** [comment]
Hmm.. I wonder if lambda no longer has setuptools installed by default. I'll re-open this ticket as a reminder to investigate that.

**Comment by Pjack** [comment]
Setuptools is installed by default in lambda, but the version seems old, something like that. 
Anyway, pkg_resources/ is not available in lambda that we have to install latest setuptools to solve the problem.

**Comment by psprowls** [comment]
having the same problem.   anyone have any suggestions?    setuptools is not in my .serverless/requirements directory

**Comment by miketheman** [comment]
#Triage 
In order to effectively triage and assess this, do any of the reporters have an example of a project configuration and requirements.txt that needs the pkg resources?

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
