### ISSUE TITLE
Use bind mounts via mount flag

### ISSUE THREAD

**Issue by heri16** [serverless/serverless-python-requirements#205]
https://docs.docker.com/storage/bind-mounts/#choosing-the--v-or---mount-flag

If you use -v or --volume to bind-mount a file or directory that does not yet exist on the Docker host, -v creates the endpoint for you. It is always created as a directory.

If you use --mount to bind-mount a file or directory that does not yet exist on the Docker host, Docker does not automatically create it for you, but generates an error. This error is desirable in our case.

**Comment by dschep** [comment]
Oh, cool, i wasn't familliar with that option

**Comment by heri16** [comment]
Shall we switch over to the mount flag?

**Comment by dschep** [comment]
Yes. Feel free to make a PR.

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
