### ISSUE TITLE
verbose output

### ISSUE THREAD

**Issue by dschep** [serverless/serverless-python-requirements#27]
add an option (maybe triggerd on serverless' own `-v`) to show the pip stdout and stderr

**Comment by danielsig727** [comment]
I use pip with `-v` and `--log` to dump the logs. For example:
```
    pipCmdExtraArgs:
      - '-v'
      - '--log'
      - 'pip.log'
```
And after running, the `pip.log` will be in the same directory as `serverless.yaml`.

**Comment by AndrewFarley** [comment]
+1 @danielsig727 nice, if there's no argument to this, I think this should probably be enabled by default from this plugin, and as mentioned above, only actually printed to the screen if verbose/debug mode is enabled and/or mail tail that log if the plugin fails to run pip

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
