### ISSUE TITLE
Cannot require cryptography 2.4.1

### ISSUE THREAD

**Issue by montao** [serverless/serverless-python-requirements#280]
PyMySQL which we use depends on cryptography and cryptography upgraded this week to new release 2.4.1 which for some reason breaks deployment. We had to fix the version to cryptography==2.3.1 to succeed with deployment. I tried reproducing it by installing manually the packages in an Amazon Linux Image but then everything installed. But it is reproducible when you try and deploy a project using the latest version of PyMySQL. The error message is complaining about cffi (C Foreign Function Interface for Python) not being compatible with the environment. 

How can we resolve this so that we can run the latest version?

**Comment by dschep** [comment]
Interesting. What OS are you on, are you using `dockerizePip`, and which python runtime are you using (2.7 or 3.6)?

I tested with [dschep-bug-repos/sls-py-req-280](https://github.com/dschep-bug-repos/sls-py-req-280) with out issues:
```
$ sls invoke -f hello
{
    "statusCode": 200,
    "cryptography version": "2.4.1",
    "body": "{\"message\": \"Go Serverless v1.0! Your function executed successfully!\", \"input\": {}}"
}
```

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
