### ISSUE TITLE
Feature request: pythonBin fallback logic

### ISSUE THREAD

**Issue by et304383** [serverless/serverless-python-requirements#307]
It would be nice if this plugin behaved like serverless-wsgi when the pythonBin value default of the runtime isn't found.

In other words, if runtime is python3.7 and this isn't found on $PATH, having this plugin fallback to just **python** as serverless-wsgi does.

THis would be very useful for the common scenario of using virtual environments to run serverless.  In that case, the python bin value is always python, regardless of the runtime value.

Thanks in advance!

**Comment by dschep** [comment]
That's a good idea :+1:

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
