### ISSUE TITLE
Native code dependencies issue (libmysqlclient.so.1020)

### ISSUE THREAD

**Issue by polosatyi** [serverless/serverless-python-requirements#317]
Hi, guys! 
I need to launch a lambda function that uses `mysqlclient==1.4.2` and `SQLAlchemy==1.2.16`.
I followed your instructions and got an error:
```ImportError: /var/task/libmysqlclient.so.1020: symbol X509_check_ip_asc, version libcrypto.so.10 not defined in file libcrypto.so.10 with link time reference```
I tried to use docker images: `amazonlinux:1` (as you suggested) and `amazonlinux:2017.03.1.20170812`. And I got the same result.
Does anyone know how to solve my problem?

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
