### ISSUE TITLE
Namespace packages don't work

### ISSUE THREAD

**Issue by dschep** [serverless/serverless-python-requirements#32]
`pip install --target` which this plugin uses has issues with namespace packages as @marcoromelli observed in #3.

**Comment by dschep** [comment]
There are some ideas in https://github.com/pypa/pip/issues/1924 that could help. Would probably need a helper script that has to explicitly be imported however :cry: (similar to `unzip_requirements.txt`)

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
