### ISSUE TITLE
Compile-Only python packages

### ISSUE THREAD

**Issue by ecurtin2** [serverless/serverless-python-requirements#325]
Hello, 

I just stumbled across this plugin. I've been manually doing some of the stuff that is accomplished by the plugin, and while I was experimenting I've found that compiling python packages with

`python -m compileall $package_root`

then removing the source code can significantly impact the distribution size of the library and doesn't effect behavior (that I've noticed, at least)

Is there interest in adding this as a feature here?

**Comment by dschep** [comment]
That's a good idea! I'd probably accept a PR implementing that :)

**Comment by ecurtin2** [comment]
Awesome! Right now I'm doing it in from python but I'll give it a shot with what you all have going here

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
