### ISSUE TITLE
file (development) dependency of another file dependency is ignored

### ISSUE THREAD

**Issue by petergaultney** [serverless/serverless-python-requirements#349]
In my application - we'll call it `peterapp` - I use two locally-developed, privately published library packages, we'll call them `core` and `apputils`.  

`core` has no significant `install_requires` dependencies.  `apputils`, however, depends upon `core`, and in its `setup.py` it defines that dependency as `core >= 1.0.0`.

I use `Pipenv` to lock dependency versions for `peterapp`. For releases, the Pipfile specifies the exact versions of both packages.

However, when developing, it is often necessary to pull in local copies of one or both library packages. This can be done fairly easily by changing the `Pipfile` to point to the local filesystem path: 
```
core = {file = "file:///Users/peter/workspace/python-packages/Core/"}
apputils = {file = "file:///Users/peter/workspace/python-packages/AppUtils/"}
```

Running `pipenv install` correctly locates and installs the current local copy of _both_ packages, and it correctly puts local filepaths for both packages into the `Pipfile.lock`.

However, `serverless-python-requirements` has a different behavior. When it packages up the requirements for my Lambdas, it *only* packages up the local copy of `apputils`. The `core` version installed is the most recent published version rather than the local copy, apparently because `serverless-python-requirements` finds `apputils`'s requirement first, and finds something that satisfies that requirement, and then does not bother with the pinned local file requirement in the `Pipfile.lock`.

I've attached the relevant Pipfile.lock as well as the debug output of serverless-python-requirements.  I would love to have a solution that allows me to develop against this small package hierarchy without having to edit my `serverless.yml` - right now the only workaround seems to be using a completely different deployment strategy for development vs production, which is quite painful.
[serverless_debug_deploy.txt](https://github.com/UnitedIncome/serverless-python-requirements/files/3090567/spr.txt)
[Pipfile.lock](https://github.com/UnitedIncome/serverless-python-requirements/files/3090569/Pipfile.lock.txt)

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
