### ISSUE TITLE
Per-function requirements DockerFile

### ISSUE THREAD

**Issue by engmsaleh** [serverless/serverless-python-requirements#368]
I was wondering if I could use `Per-function requirements` with separate **DockerFile** for each module if I have multiple modules in the same Serverless.yml file

**Comment by dschep** [comment]
That is not currently supported

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
