### ISSUE TITLE
How to handle python modules in a Node.js serverless framework?

### ISSUE THREAD

**Issue by nicolasesnis** [serverless/serverless-python-requirements#381]
I'm working on a nodejs10.x serverless project. My handler.js file calls some Python scripts to run data processing and requires to import external modules (Numpy, Pandas, etc.). I've installed these modules in the project virtualenv and added them into a requirements.txt. I've tried to handle these modules with serverless-python-requirements but I've faced problems with Docker:

`Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"nodejs10.x\": executable file not found in $PATH": unknown.`

I believe this is because I'm trying to install Python packages in a Node project. Any help on insight on this would be appreciated.

**Comment by cl0ckwork** [comment]
It appears `serverless-python-requirements` reads from the `provider.runtime` field to build your packaging container.


`provider.runtime` = `python3.7` -> `Serverless: Docker Image: lambci/lambda:build-python3.7` 
vs
`provider.runtime` = `nodejs10.x` ->`Serverless: Docker Image: lambci/lambda:build-nodejs10.x`

If you dont need it there, remove the `nodejs10.x` runtime from that global position and place it into each function, place your python version there. This should solve your issue.
 
```
provider:
  name: aws
  runtime: python3.7
```

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
