### ISSUE TITLE
Individually at function level

### ISSUE THREAD

**Issue by ed-sparkes** [serverless/serverless-python-requirements#383]
Hi, 

Does this support the individually flag a the package level rather than service level? 

I have a project which is predominantly node functions with one or two python functions. I dont want to package individually across the whole service as webpack is bundling all my node stuff, however i do for the python bits. I have followed the example for individual packaging but set the flag under the desired functions but i get an error 

`The "path" argument must be one of type string, Buffer, or URL. Received type undefined`

when it is trying to `Injecting required Python packages to package...`

**Comment by mojimi** [comment]
It looks like it doesn't, it doesn't automatically search for the requirements.txt in the function module folder

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
