### ISSUE TITLE
layer support for individually:true + separate requirements.txt

### ISSUE THREAD

**Issue by vladislav-stolyarov** [serverless/serverless-python-requirements#408]
This pseudosetup doe not work with layers
pythonRequirements:
    layer: true
package:
   individually: true
function-xxx:
   module: folder_with_function_and_requirements_txt
function-yyy:....

 Error: ENOENT: no such file or directory, scandir 'C:\Users\vladislav.stolyarov\source\repos\SampleLambda\functions\.serverless\requirements'

How can i utilize layers advantage in individual requirements.txt per function scenario?
I tried putting single requirements.txt to the root but it is ignored.
I tried creating extra stub function in the root next to it to hack, this helped but now i have to deploy extra function with my layer inside using this hack:
functions:
  function-deploy-layer:..does nothing..
layers:
  pythonRequirements:
    path: '.serverless/requirements' # That is a hack

Using pythonRequirements layer:true instead of layers: does not work properly

Any solutions to my problem? Is it possible to utilize layers support with(next to) individual functions?

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
