### ISSUE TITLE
Failing docker builds will leave files owned as root

### ISSUE THREAD

**Issue by Shados** [serverless/serverless-python-requirements#421]
https://github.com/UnitedIncome/serverless-python-requirements/blob/c9d910cc40d95163f8894abfdefaf9c4fc33b505/lib/pip.js#L264-L269

^ This code never gets run if during the `docker-run` one of the Python package builds fails (e.g. due to missing some system dependency).

This will leave the download cache files owned by root, which will in turn prevent subsequent build attempts from working, due to this [earlier attempt](https://github.com/UnitedIncome/serverless-python-requirements/blob/c9d910cc40d95163f8894abfdefaf9c4fc33b505/lib/pip.js#L223) to open `$downloadCacheDir/requriements.txt` in write mode now being unable to succeed.

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
