### ISSUE TITLE
Dependency packaging for layers

### ISSUE THREAD

**Issue by Procrat** [serverless/serverless-python-requirements#433]
This is probably more of a feature request than a bug, but I noticed that currently this plugin only supports bundling dependencies for Lambda functions. It would be great if it also did this for Lambda layers.

To make it concrete, if `serverless.yml` contains a definition of a layer:
```
(...)

layers:
  my-layer:
    path: my-layer
```
and there is a requirements file in `my-layer/requirements.txt`, the dependencies would get installed as part of the packaging of the layer.

There seems to be a `package:compileLayers` hook that could be useful here.

Thank you for considering this!

**Comment by jimpudar** [comment]
I also expected this. I don't currently see any way to use this plugin to install dependencies for multiple layers - please correct me if I'm wrong.

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
