### ISSUE TITLE
Plugin creates packages even though I'm using Lambda Layers

### ISSUE THREAD

**Issue by Jordan-Eckowitz** [serverless/serverless-python-requirements#450]
I'm using the per function setup shown here in the README:
https://github.com/UnitedIncome/serverless-python-requirements#per-function-requirements

I've switched to using Layers to reduce my deployment time. So all of the individual `requirements.txt` files are now empty. But when I deploy the API, this plugin still runs the packaging process.

I'm guessing its reading the imports inside the `py` files in each sub-folder and packaging those imports. Is there a way to skip python packaging if the individual `requirements.txt` files are empty?

**Comment by farridav** [comment]
I have run into the same issue, and I'm *not* using per-function requirements, it seems it still adds the `.requirements.zip` to the deployment payload, also worth asking, do you still have to use `import unzip_requirements` in the same way ? Id love to see some more documentation on the use of layers with this plugin.. Ta

**Comment by Jordan-Eckowitz** [comment]
Any updates on this issue?

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
