### ISSUE TITLE
Configuration warning at 'xxxxxxxx': unrecognized property 'module'

### ISSUE THREAD

**Issue by rcedwardsiii** [serverless/serverless-python-requirements#587]
Using serverless-python-requirements plugin results in the a configuration warning when using the 'module' property. It appears the plugin needs to provide the schema for the new validator in 2.x (testing with Framework Core: 2.18.0) 

https://www.serverless.com/framework/docs/configuration-validation/

> If you received a configuration warning it could mean that:
>
>- Service configuration is invalid and you need to correct an issue related to your serverless.yml
>- Configuration related to external plugin does not have an **associated JSON Schema.** In such cases, please report the issue with the plugin author and provide them the details on how to extend validation schema in order to permanently correct the issue.
>- However unlikely, there may be a bug (or missing) schema configuration for the framework. If you believe this to be the case please report at https://github.com/serverless/serverless/issues/new

**Comment by hortonew** [comment]
Are there any plans to resolve this?

**Comment by benjy** [comment]
It looks like there is a new way to `defineFunctionProperties` in Serverless: https://github.com/serverless/serverless/pull/8462

**Comment by rileypriddle** [comment]
this has been merged #641
