### ISSUE TITLE
Dependency `lodash.set` has an unpatched CVE

### ISSUE THREAD

**Issue by mhassan1** [serverless/serverless-python-requirements#675]
The [lodash.set](https://www.npmjs.com/package/lodash.set) package has an open CVE: https://security.snyk.io/vuln/SNYK-JS-LODASHSET-1320032. The maintainer of Lodash will not release a patched version, and he considers the per-method packages [soft-deprecated](https://github.com/lodash/lodash/issues/3793#issuecomment-389774153).

We should be able to use [set-value](https://www.npmjs.com/package/set-value) as a drop-in replacement.

**Comment by mhassan1** [comment]
Thanks, @pgrzesik. When do we think this will get an NPM release?

**Comment by pgrzesik** [comment]
Hello @mhassan1 - I'm waiting for 1 PR to be completed - I would expect it to be released sometime later this week.
