### ISSUE TITLE
reference.json mismatch for slimPatterns

### ISSUE THREAD

**Issue by alanwilter** [serverless/serverless-python-requirements#733]
[Here](https://github.com/serverless/serverless-python-requirements#custom-removal-patterns) says:

```yaml
custom:
  pythonRequirements:
    slim: true
    slimPatterns:
      - '**/*.egg-info*'
```

But my vscode is complaining with

```json
[{
	"resource": ".../serverless.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Incorrect type. Expected \"string\".",
	"source": "yaml-schema: Serverless Framework Configuration",
	"startLineNumber": 85,
	"startColumn": 7,
	"endLineNumber": 101,
	"endColumn": 1
}]
```

And if I see the `reference.json` for `slimPatterns`:

```json
        "slimPatterns": {
          "type": "string",
          "description": "https://github.com/serverless/serverless-python-requirements#custom-removal-patterns"
        },
```

I can see something is wrong. Now what's wrong? Should it be an array? like:

```json
        "slimPatterns": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
``` 

or how to do it with strings?

**Comment by pgrzesik** [comment]
Hello @alanwilter - thanks a lot for reporting. You mention that your "VSCode is complaining" - could you please elaborate more? What exactly are you using along with VSCode to check the configuration?

**Comment by alanwilter** [comment]
From `serverless.yml` in `VSCode`:

Wiggled red lines -> problems!
<img width="513" alt="Screenshot 2022-10-22 at 08 13 13" src="https://user-images.githubusercontent.com/3899850/197325975-ab1fa6df-809a-422e-936e-95b7470dad27.png">

Hovering over -> shows the reason
<img width="1164" alt="Screenshot 2022-10-22 at 08 17 22" src="https://user-images.githubusercontent.com/3899850/197326113-1e29cbc4-09be-49ea-91dc-5114ba1e2ceb.png">

Right-click takes me to the `reference.json`
<img width="490" alt="Screenshot 2022-10-22 at 08 21 02" src="https://user-images.githubusercontent.com/3899850/197326211-aa13a846-6a42-485a-908b-9a1151a0b345.png">

<img width="1179" alt="Screenshot 2022-10-22 at 08 23 21" src="https://user-images.githubusercontent.com/3899850/197326301-bcfeb25a-d660-48e0-9bba-1816bd48d686.png">

Now, I don't know where `reference.json` comes from. If from `serverless-python-requirements` or from a `VSCode` plugin.

**Comment by alanwilter** [comment]
Ok, it's not `serverless-python-requirements`, it's in

```json
  "$schema": "https://json-schema.org/draft-07/schema#",
  "title": "Serverless Framework Configuration",
  "description": "Schema for serverless framework configuration files",
  "fileMatch": ["serverless.yml", "serverless.yaml"],
```

**Comment by pgrzesik** [comment]
Hey @alanwilter - it looks like it's an issue with the VSCode plugin and it would be better to report it at that plugin's repo - unfortunately I don't know which plugin are you using exactly.
