### ISSUE TITLE
Release latest changes please

### ISSUE THREAD

**Issue by andidev** [serverless/serverless-python-requirements#786]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you using the latest plugin release?

- [X] Yes, I'm using the latest plugin release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Can someone please release latest changes so we can use this plugin again?

Currently we have to import plugin like this
```
"serverless-python-requirements": "git://github.com/serverless/serverless-python-requirements.git#c1f5ca114de815ca19ad213a79e250b5b81f29b3"
```

would be nice to get this and other prs out
https://github.com/serverless/serverless-python-requirements/pull/780

sorry for filing a bug about this but not sure what to do.
Or maybe there is a plan for a release in near future?

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless deploy --stage dev

### Command output

```shell
✖ Stack pidedirectoanalyticsserver-dev failed to deploy (0s)
Environment: darwin, node 16.17.0, framework 3.22.0 (local), plugin 6.2.2, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: `pipenv lock --keep-outdated` Exited with code 1
    at ChildProcess.<anonymous> (/Users/anders/Workspace/swedishtechnologies/pidedirectoanalyticsserver/node_modules/child-process-ext/spawn.js:38:8)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

### Environment information

```shell
Framework Core: 3.22.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by jaswanthikolla** [comment]
This is blocking everyone, and there are 11 votes. Can you please release a new version.

**Comment by jgiudici-vt** [comment]
Hey can you make a release with this?

**Comment by pgrzesik** [comment]
Yes, sorry about the delay around this - sometimes there are too many things to deal with and not enough time for open source contribs. You can expect a new release to be out this week. 👍

**Comment by ydinari** [comment]
Hi, any update about the release?
Thanks

**Comment by pgrzesik** [comment]
Hey @ydinari, I was preparing the release yesterday, but there's an issue with current CI test runs which prevented me from releasing the package. I will be debugging it further later today 👍

**Comment by yucealiosman** [comment]
Hello, is there any update about the release? Thanks.

**Comment by pgrzesik** [comment]
Hello, there is an update, but unfortunately, it's not a great one. After resolving the issues with current tests/CI setup, it turned out that current CI is failing on publish. After more investigation, I'm fairly sure that it's due to outdated/revoked npm token. Unfortunately, I don't have full access to this repo and I don't have any administrative access to this project on `npm`. I've reached out to `serverless` team about that and until they respond I'm blocked with any releases. I'll keep everyone posted if/when I get a response from the team. I'm hoping to get access at least on `npm`, so I could publish a release on my own.

**Comment by pgrzesik** [comment]
Hey all 👋 Fortunately, Serverless team was very responsive and quickly granted me extended access to the repo & npm package, which allowed me to release 6.0.1 🙌 Once again, sorry for the delay on this one
