### ISSUE TITLE
Serverless Framework version 4 support?

### ISSUE THREAD

**Issue by et304383** [serverless/serverless-python-requirements#845]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

I want to use this plugin with serverless framework v4.  I am surprised this issue has not come up yet.

The install fails on dependencies:

```
sls plugin install -n serverless-python-requirements
✖ npm ERR! code ERESOLVE
  npm ERR! ERESOLVE unable to resolve dependency tree
  npm ERR! 
  npm ERR! While resolving: undefined@undefined
  npm ERR! Found: serverless@4.1.11
  npm ERR! node_modules/serverless
  npm ERR!   dev serverless@"4" from the root project
  npm ERR! 
  npm ERR! Could not resolve dependency:
  npm ERR! peer serverless@"^2.32 || 3" from serverless-python-requirements@6.1.0
  npm ERR! node_modules/serverless-python-requirements
  npm ERR!   dev serverless-python-requirements@"6.1.0" from the root project
  npm ERR! 
  npm ERR! Fix the upstream dependency conflict, or retry
  npm ERR! this command with --force or --legacy-peer-deps
  npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
  npm ERR! 
```

**Comment by Tsingis** [comment]
As npm suggests `--force` and `--legacy-peer-deps` are at least current workaround. Not ideal at all though.

**Comment by czubocha** [comment]
Hey, thanks for raising this issue. Just a heads up - a [new version](https://github.com/serverless/serverless-python-requirements/releases/tag/v6.1.1) that supports Serverless Framework v4 has been released.
